name: Nilakkhana changed files

on:
  push:
    branches:
      - fix-sync-failed

jobs:
  build:
    runs-on: ubuntu-latest
    name: Nilakkhana-changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5

      - name: Run Nilakkhana transform only on changed files
        if: steps.changed-files.outputs.all_changed_files
        run: python .nilakkhana/per_file_parse.py -f ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Push changed files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Nilakkhana changed files"
          git push origin fix-sync-failed:fix-sync-failed
