name: Push File

on:
  push:
    branches:
      - "fix-sync-failed"

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Pushes files to sc_data repo
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        src_branch: fix-sync-failed
        src_path: /.
        dst_path: /sc_bilara_data/
        clean: true
        dst_owner: suttacentral
        dst_repo_name: sc-data
        dst_branch: fix-sync-failed
        commit_message: '[GHA] Update the bilara_data files.'
