name: Sync all changed files to sc-data

on:
  push:
    branches:
      - "fix-sync-failed"

jobs:
  sync-changed-files-to-sc-data:
    runs-on: ubuntu-latest
    steps:
    - name: Sync changed files to sc-data repo
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        src_branch: fix-sync-failed
        src_path: /.
        dst_owner: suttacentral
        dst_repo_name: sc-data
        dst_path: /sc_bilara_data/
        dst_branch: fix-sync-failed
        clean: true
        commit_message: '[GHA] Update the bilara_data files.'
